### ISSUE TITLE
Type hints not accessible in mypy

### ISSUE THREAD

**Issue by kislyuk** [mnot/http_sfv#8]
Thank you for writing this package, it is very useful. I am running into the following error when running mypy on a dependency:

> error: Skipping analyzing "http_sfv": module is installed, but missing library stubs or py.typed marker

It would be great to include `py.typed` in future releases, since the package already seems to include type hints and pass mypy checks.

**Comment by mnot** [comment]
I _think_ I did that correctly in 0.9.4 just now - give it a try?

**Comment by kislyuk** [comment]
Unfortunately it's not working. I think the py.typed file is not included in the distribution:
```
http https://files.pythonhosted.org/packages/52/af/d52c9a5dabe860139d96d9b3e9e9ed99fcb8f7b220bb969b5f540b3a8255/http_sfv-0.9.4.tar.gz | tar -xvz
x http_sfv-0.9.4/
x http_sfv-0.9.4/LICENCE.md
x http_sfv-0.9.4/PKG-INFO
x http_sfv-0.9.4/README.md
x http_sfv-0.9.4/http_sfv/
x http_sfv-0.9.4/http_sfv/__init__.py
x http_sfv-0.9.4/http_sfv/__main__.py
x http_sfv-0.9.4/http_sfv/boolean.py
x http_sfv-0.9.4/http_sfv/byteseq.py
x http_sfv-0.9.4/http_sfv/decimal.py
x http_sfv-0.9.4/http_sfv/dictionary.py
x http_sfv-0.9.4/http_sfv/integer.py
x http_sfv-0.9.4/http_sfv/item.py
x http_sfv-0.9.4/http_sfv/list.py
x http_sfv-0.9.4/http_sfv/string.py
x http_sfv-0.9.4/http_sfv/token.py
x http_sfv-0.9.4/http_sfv/types.py
x http_sfv-0.9.4/http_sfv/util.py
x http_sfv-0.9.4/http_sfv/util_json.py
x http_sfv-0.9.4/http_sfv.egg-info/
x http_sfv-0.9.4/http_sfv.egg-info/PKG-INFO
x http_sfv-0.9.4/http_sfv.egg-info/SOURCES.txt
x http_sfv-0.9.4/http_sfv.egg-info/dependency_links.txt
x http_sfv-0.9.4/http_sfv.egg-info/requires.txt
x http_sfv-0.9.4/http_sfv.egg-info/top_level.txt
x http_sfv-0.9.4/pyproject.toml
x http_sfv-0.9.4/setup.cfg
x http_sfv-0.9.4/test/
x http_sfv-0.9.4/test/test.py
x http_sfv-0.9.4/test/test_api.py
x http_sfv-0.9.4/test/test_perf.py
```
This is probably because it was placed in the top level repo directory, not in the package subdirectory (http_sfv/http_sfv/py.typed).

**Comment by mnot** [comment]
Argh. OK, try 0.9.5.

**Comment by kislyuk** [comment]
It works now! Thank you!!!

FYI I'm using this to parse and validate HTTP signatures (https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures).
